GL Strings - sync config files

diff --git a/.github/workflows/applanga-push.yml b/.github/workflows/applanga-push.yml
--- a/.github/workflows/applanga-push.yml
+++ b/.github/workflows/applanga-push.yml
@@ -38,8 +38,6 @@ jobs:
       - uses: applanga/setup-applanga-cli@v1.0.3
         with:
           version: 1.0.*
-      - name: sleep 30
-        run: sleep 20
       - name: Push Sources to Applanga
         if: '${{ inputs.push_targets != true }}'
         env:
@@ -53,19 +51,19 @@ jobs:
           APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
         run: applanga pushtarget --force
         working-directory: checkout
-      # - name: Notify workflow success
-      #   if: success()
-      #   run: |-
-      #     curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ steps.extract-app-id.outputs.MOBILE_APP_ID }}" \
-      #       -H "Content-Type: application/json" \
-      #       -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
-      #       -d '{
-      #       "branchId": "${{ github.event.inputs.branch_id }}",
-      #       "workflowType": "push",
-      #         "status": "success"
-      #       }' || echo "Failed to notify workflow success"
+      - name: Notify workflow success
+        if: success()
+        run: |-
+          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ steps.extract-app-id.outputs.MOBILE_APP_ID }}" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
+            -d '{
+            "branchId": "${{ github.event.inputs.branch_id }}",
+            "workflowType": "push",
+              "status": "success"
+            }' || echo "Failed to notify workflow success"
       - name: Notify workflow failure
-        # if: failure()
+        if: failure()
         run: |-
           curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ steps.extract-app-id.outputs.MOBILE_APP_ID }}" \
             -H "Content-Type: application/json" \
