Update applanga-pull.yml branching test

diff --git a/.github/workflows/applanga-pull.yml b/.github/workflows/applanga-pull.yml
--- a/.github/workflows/applanga-pull.yml
+++ b/.github/workflows/applanga-pull.yml
@@ -50,6 +50,8 @@ jobs:
       - uses: applanga/setup-applanga-cli@v1.0.3
         with:
           version: 1.0.*
+      - name: wait 15 seconds
+        run: sleep 15
       - name: Pull translations from Applanga
         env:
           APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
@@ -66,17 +68,17 @@ jobs:
           title: ${{ github.event.inputs.pr_title }}
           body: Pulled in new translations from Applanga portal
           path: checkout
-      # - name: Notify workflow success
-      #   if: success()
-      #   run: |-
-      #     curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/${{ github.event.inputs.mobileAppId }}/workflow-complete" \
-      #       -H "Content-Type: application/json" \
-      #       -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
-      #       -d '{
-      #         "branchId": "${{ github.event.inputs.branchId }}",
-      #         "workflowType": "pull",
-      #         "status": "success"
-      #       }' || echo "Failed to notify workflow success"
+      - name: Notify workflow success
+        if: success()
+        run: |-
+          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/${{ github.event.inputs.mobileAppId }}/workflow-complete" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
+            -d '{
+              "branchId": "${{ github.event.inputs.branchId }}",
+              "workflowType": "pull",
+              "status": "success"
+            }' || echo "Failed to notify workflow success"
       - name: Notify workflow failure
         if: ${{ failure() }}
         run: |-
