GL Strings - sync config files

diff --git a/.github/workflows/applanga-push.yml b/.github/workflows/applanga-push.yml
--- a/.github/workflows/applanga-push.yml
+++ b/.github/workflows/applanga-push.yml
@@ -12,6 +12,10 @@ on:
         description: Push translation files. If set translation files will be pushed instead of source files
         default: false
         required: false
+      mobileAppId:
+        description: Mobile App ID (MongoDB _id)
+        required: true
+        type: string
       branchId:
         description: Branch ID (optional)
         required: false
@@ -22,7 +26,7 @@ jobs:
     steps:
       - name: Notify workflow started
         run: |-
-          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/workflow-start" \
+          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/${{ github.event.inputs.mobileAppId }}/workflow-start" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
             -d '{
@@ -51,7 +55,7 @@ jobs:
       - name: Notify workflow success
         if: success()
         run: |-
-          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/workflow-complete" \
+          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/${{ github.event.inputs.mobileAppId }}/workflow-complete" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
             -d '{
@@ -62,11 +66,11 @@ jobs:
       - name: Notify workflow failure
         if: failure()
         run: |-
-          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/workflow-complete" \
+          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v2/projects/${{ github.event.inputs.mobileAppId }}/workflow-complete" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
             -d '{
             "branchId": "${{ github.event.inputs.branchId }}",
             "workflowType": "push",
               "status": "failed"
-             }' || echo "Failed to notify workflow failure"
+            }' || echo "Failed to notify workflow failure"
