GL Strings - sync config files

diff --git a/.github/workflows/applanga-push.yml b/.github/workflows/applanga-push.yml
--- a/.github/workflows/applanga-push.yml
+++ b/.github/workflows/applanga-push.yml
@@ -12,8 +12,8 @@ on:
         description: Push translation files. If set translation files will be pushed instead of source files
         default: false
         required: false
-      branch_id:
-        description: Branch ID
+      applanga_branch_id:
+        description: Applanga Project Branch ID
         required: false
         type: string
 jobs:
@@ -24,7 +24,7 @@ jobs:
         id: api_config
         env:
           ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
-          BRANCH_ID_INPUT: '${{ github.event.inputs.branch_id }}'
+          BRANCH_ID_INPUT: '${{ github.event.inputs.applanga_branch_id }}'
           APPLANGA_API_HOST: ${{ secrets.APPLANGA_API_HOST }}
         run: |-
           # Set API host from secret or use fallback, then remove any trailing slash
@@ -71,23 +71,23 @@ jobs:
           APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
         run: applanga pushtarget --force
         working-directory: checkout
-      # - name: Notify workflow success
-      #   if: success()
-      #   run: |-
-      #     curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-complete?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
-      #       -H "Content-Type: application/json" \
-      #       -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
-      #       -d '{
-      #       "workflowType": "push",
-      #         "status": "success"
-      #       }' || echo "Failed to notify workflow success"
-      # - name: Notify workflow failure
-      #   # if: failure()
-      #   run: |-
-      #     curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-complete?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
-      #       -H "Content-Type: application/json" \
-      #       -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
-      #       -d '{
-      #       "workflowType": "push",
-      #         "status": "failed"
-      #       }' || echo "Failed to notify workflow failure"
+      - name: Notify workflow success
+        if: success()
+        run: |-
+          curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-complete?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
+            -d '{
+            "workflowType": "push",
+              "status": "success"
+            }' || echo "Failed to notify workflow success"
+      - name: Notify workflow failure
+        if: failure()
+        run: |-
+          curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-complete?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
+            -d '{
+            "workflowType": "push",
+              "status": "failed"
+            }' || echo "Failed to notify workflow failure"
